### ISSUE TITLE
Add option to "select all" in the duplicate contact removal page. 

### ISSUE THREAD

**Issue by rasheedsulayman** [rasheedsulayman/DuplicateContactsRemover#8]
Currently, users can only scroll down to select contacts to remove. This feature should allow users to click on a toolbar menu option to "select all" contacts to remove.

Also, users are requesting for this feature on Playstore

**Comment by r4sh33d** [comment]
![Screenshot_2020-02-21-10-26-06](https://user-images.githubusercontent.com/12248357/75022525-83209680-5496-11ea-9b81-0d7b3c5e0dbf.png)

The select all checkbox should be placed in the highlighted area in the attached screenshot.

**Comment by rasheedsulayman** [comment]
Fixed in https://github.com/rasheedsulayman/DuplicateContactsRemover/pull/9
